# /api-bridge/app/constants.py
ONE_DAY_IN_SECONDS = 60 * 60 * 24
HALF_DAY_IN_SECONDS = 60 * 60 * 12
ONE_HOUR_IN_SECONDS = 60 * 60
WEATHER_CACHE_TIMEOUT = ONE_HOUR_IN_SECONDS
CITY_SEARCH_CACHE_TIMEOUT = ONE_DAY_IN_SECONDS
